"""Concise editorial guidance; official destinations verified 2026-10-03."""
TOOLS=[
 ('Google Flow','Rangkai ide dan scene dalam workflow video Google.','https://labs.google/flow/','Video'),
 ('Higgsfield','Eksplorasi workflow kreator, iklan, dan arahan kamera.','https://higgsfield.ai/','Video'),
 ('Runway','Pembuatan dan pengolahan klip untuk kebutuhan kreatif.','https://runwayml.com/','Video'),
 ('Seedance','Pelajari model dan akses layanan yang ditautkan oleh ByteDance Seed. Ketersediaan mengikuti layanan tersebut.','https://seed.bytedance.com/en/seedance','Video'),
 ('CapCut','Susun klip, tambahkan caption dan audio untuk konten sosial.','https://www.capcut.com/','Editing'),
 ('Adobe Premiere','Editing akhir, penyusunan sequence, audio dan ekspor.','https://www.adobe.com/products/premiere.html','Editing'),
]
LESSONS=[
 ('Mulai dari text-to-video','Jelaskan subjek, aksi, tempat dan kamera. Satu aksi utama per klip lebih mudah diarahkan.',
  'Buat orang minum kopi.','Vertikal 9:16. Perempuan Indonesia duduk dekat jendela kafe, mengangkat cangkir kopi. Kamera medium shot stabil, cahaya pagi lembut.','Subjek, aksi, framing dan cahaya memberi arahan yang bisa dilaksanakan.'),
 ('Image-to-video','Gunakan foto sebagai titik awal. Prompt menjelaskan gerakan, bukan mendesain ulang produk.',
  'Bikin sepatu ini keren.','Pertahankan sepatu dalam referensi. Kamera bergerak perlahan mendekati detail jahitan, sepatu tetap diam.','Arahan gerak jelas tanpa meminta bentuk sepatu berubah.'),
 ('Pilih referensi yang jelas','Foto tajam, latar sederhana dan produk terlihat utuh membantu menjaga identitas. Pisahkan referensi produk dan referensi gaya.',
  'Ikuti semua foto ini.','Foto pertama adalah produk yang harus tetap sama. Foto kedua hanya referensi pencahayaan.','Peran tiap referensi tidak tercampur.'),
 ('Orang dan pakaian tetap sama','Tuliskan ciri karakter dan pakaian secara konsisten. Gunakan referensi yang sama antar-klip.',
  'Orangnya sama.','Pertahankan perempuan dari referensi, rambut sebahu dan kemeja putih yang sama pada semua scene.','Ciri yang konsisten membantu mengurangi pergantian identitas.'),
 ('Jaga identitas produk','Sebutkan bagian yang harus dipertahankan. Tambahkan logo atau teks yang presisi di tahap editing bila generasi tidak akurat.',
  'Produknya jangan berubah.','Pertahankan bentuk botol, warna tutup dan posisi label sesuai foto. Jangan menambahkan tulisan baru.','Bagian penting produk diberi batas yang konkret.'),
 ('Gerakan kamera','Pilih gerakan yang punya tujuan. Kamera diam cocok untuk demo; push-in menonjolkan detail.',
  'Kamera heboh.','Kamera statis saat produk dipakai, lalu push-in ringan ke detail produk.','Gerakan mendukung informasi, bukan mengambil alih perhatian.'),
 ('Cahaya dan mood','Tentukan sumber cahaya, arah dan suasana. Jangan mencampur banyak gaya tanpa tujuan.',
  'Lighting bagus.','Cahaya jendela lembut dari kiri, bayangan halus dan warna kulit natural.','Sumber dan arah cahaya lebih jelas daripada kata bagus.'),
 ('B-roll yang berguna','B-roll mendukung cerita: detail, aktivitas tangan, tempat atau proses. Hindari shot cantik yang tidak menjelaskan apa pun.',
  'Tambahkan B-roll.','Sisipkan close-up tekstur kemasan dan tangan meletakkan produk sebelum hero shot.','Shot pendukung terhubung dengan produk dan alur.'),
 ('UGC terasa natural','Pakai kamera setinggi mata, gerak ringan dan bahasa percakapan. Demonstrasi nyata lebih berguna daripada kamera dramatis.',
  'UGC cinematic banget.','Kreator berbicara santai ke kamera ponsel, menunjukkan cara memakai produk dengan framing medium.','Pilihan kamera cocok dengan format kreator sehari-hari.'),
 ('Iklan produk','Susun pembuka, demonstrasi dan CTA. Gunakan hanya manfaat yang sudah terverifikasi; jangan membuat klaim baru.',
  'Produk ini pasti terbaik.','Buka dengan detail produk, tunjukkan penggunaannya, tutup dengan ajakan melihat katalog.','Iklan tetap menarik tanpa klaim yang belum terbukti.'),
 ('Arahan cinematic','Framing, cahaya dan ritme membentuk mood. Slow motion atau drone bukan syarat untuk terlihat cinematic.',
  'Semua slow motion.','Mulai wide shot tempat, lanjut medium aksi, tutup close-up detail dengan cahaya dan warna konsisten.','Variasi ukuran shot membangun cerita secara terarah.'),
 ('Storyboard sebelum produksi','Bagi cerita ke adegan bertimed: apa yang terlihat, aksi dan transisi. Jumlah scene mengikuti informasi, bukan jumlah efek.',
  'Video 10 detik penuh ide.','0–3 detik pembuka; 3–7 detik demonstrasi; 7–10 detik hero frame dan CTA.','Setiap bagian punya fungsi dan waktu yang masuk akal.'),
 ('Berapa banyak scene?','Mulai dari 2–4 adegan untuk ide singkat. Kurangi jika tiap adegan belum punya waktu untuk terbaca.',
  'Sepuluh shot dalam lima detik.','Satu shot pembuka dan satu shot produk dalam rencana lima detik.','Penonton punya waktu memahami objek utama.'),
 ('Mengapa objek berubah?','Gerak rumit, referensi tidak konsisten atau terlalu banyak perubahan dapat membuat objek bergeser. Sederhanakan satu variabel dulu.',
  'Produk berputar, melompat dan berubah tempat.','Produk diam; hanya kamera bergerak pendek. Pertahankan proporsi kemasan.','Lebih sedikit perubahan membuat evaluasi lebih mudah.'),
 ('Perbaiki hasil yang gagal','Bandingkan hasil dengan satu tujuan. Ubah arahan yang gagal, bukan seluruh prompt; coba ulang klip itu saja.',
  'Ulang semuanya.','Scene kedua: kurangi gerak kamera; pertahankan produk, talent dan pencahayaan scene pertama.','Perbaikan terukur menjaga kontinuitas yang sudah berhasil.'),
 ('Video panjang dari beberapa klip','Rencanakan keseluruhan cerita, buat klip sesuai kemampuan tool, lalu sambung di editor. Durasi rencana bukan batas generasi platform.',
  'Bikin langsung video panjang.','Rencana 30 detik dalam enam klip. Akhiri tiap klip dengan pose yang mudah disambung ke klip berikutnya.','Urutan dan titik sambung dipersiapkan sebelum editing.'),
 ('Voice-over atau teks layar?','Pilih sesuai tujuan. Video visual tidak harus memakai narasi; teks layar pendek membantu konten tanpa suara.',
  'Bacakan semua teks.','Narasi satu kalimat untuk konteks; teks layar hanya kata kunci.','Audio dan teks saling melengkapi tanpa mengulang semuanya.'),
 ('Vertikal 9:16','Tempatkan subjek utama di tengah, beri ruang caption dan antarmuka aplikasi. Periksa crop sebelum ekspor.',
  'Objek di ujung frame.','Hero produk di area tengah, sisakan ruang atas dan bawah untuk caption dan kontrol aplikasi.','Produk tetap terbaca di layar ponsel.'),
 ('Editing dan ekspor akhir','Susun klip, rapikan transisi, tambah logo/caption presisi dan audio yang berhak digunakan. Tinjau tanpa suara sebelum ekspor.',
  'Langsung unggah semua klip.','Pilih take yang konsisten, susun sesuai storyboard, cek ejaan caption dan level audio.','Pemeriksaan akhir membantu hasil terlihat utuh.'),
]
WORKFLOWS=[
 ('Iklan produk','Dari foto produk ke iklan yang jelas.',[
  'Siapkan foto produk yang tajam dan fakta/manfaat yang benar.', 'Tentukan tujuan kampanye dan audiens dalam ide video.',
  'Jika butuh referensi tambahan, buat secara terpisah di Kilas AI; jangan mengubah identitas produk.',
  'Buat Video Plan, periksa hook, storyboard dan kontinuitas.', 'Salin prompt untuk platform pilihan, lalu buat tiap klip di tool tersebut.',
  'Buat B-roll yang mendukung demonstrasi produk.', 'Susun klip di editor, tambah teks/logo presisi dan audio.', 'Periksa klaim, crop, caption dan hak audio sebelum ekspor.']),
 ('UGC','Demonstrasi yang terasa dekat dan natural.',[
  'Siapkan produk dan profil kreator tanpa mengarang pengalaman pengguna.', 'Buka dengan masalah atau situasi yang relevan.',
  'Tunjukkan penggunaan produk secara jelas.', 'Sampaikan manfaat yang sudah terverifikasi dan CTA singkat.',
  'Gunakan kamera natural, referensi kreator konsisten dan satu aksi per klip.', 'Susun klip, caption dan audio di editor; tinjau sebelum unggah.']),
 ('Cinematic','Cerita visual dengan ritme yang terarah.',[
  'Tentukan cerita, mood dan referensi gaya.', 'Buka dengan establishing shot untuk mengenalkan tempat.',
  'Lanjutkan hero/action shot dan detail yang mendukung cerita.', 'Pertahankan talent, pakaian, tempat dan cahaya antar-scene.',
  'Tutup dengan hero frame yang jelas.', 'Buat klip per scene, susun ritme dan suara di editor.']),
]
