CREATE TABLE IF NOT EXISTS kilas_agent_jobs (
 id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 title TEXT NOT NULL, instruction TEXT NOT NULL, mode TEXT NOT NULL CHECK(mode IN ('ONE_SHOT','CONTINUOUS','CONDITION_WATCH','RECURRING','SCHEDULED')),
 status TEXT NOT NULL CHECK(status IN ('PLANNING','RUNNING','WAITING','NEEDS_APPROVAL','PAUSED','COMPLETED','FAILED','STOPPED')),
 plan_json TEXT NOT NULL DEFAULT '{}', constraints_json TEXT NOT NULL DEFAULT '[]', checkpoint_json TEXT NOT NULL DEFAULT '{}',
 next_wake_at TEXT, lease_until TEXT, lease_token TEXT, revision INTEGER NOT NULL DEFAULT 0,
 max_steps INTEGER NOT NULL DEFAULT 24, max_attempts INTEGER NOT NULL DEFAULT 3,
 failures INTEGER NOT NULL DEFAULT 0, replans INTEGER NOT NULL DEFAULT 0, cycle INTEGER NOT NULL DEFAULT 0,
 interval_seconds INTEGER NOT NULL DEFAULT 3600, expires_at TEXT, last_error TEXT,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TEXT, stopped_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_due ON kilas_agent_jobs(status,next_wake_at,lease_until);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_owner ON kilas_agent_jobs(user_id,id);
CREATE TABLE IF NOT EXISTS kilas_agent_steps (
 id INTEGER PRIMARY KEY AUTOINCREMENT, job_id INTEGER NOT NULL REFERENCES kilas_agent_jobs(id) ON DELETE CASCADE,
 sequence INTEGER NOT NULL, worker TEXT NOT NULL, action TEXT NOT NULL, instruction TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','WAITING','NEEDS_APPROVAL','SKIPPED','STOPPED')),
 input_json TEXT NOT NULL DEFAULT '{}', output_json TEXT NOT NULL DEFAULT '{}', attempts INTEGER NOT NULL DEFAULT 0, requires_approval INTEGER NOT NULL DEFAULT 0,
 idempotency_key TEXT NOT NULL UNIQUE, error TEXT, started_at TEXT, completed_at TEXT, UNIQUE(job_id,sequence)
);
CREATE TABLE IF NOT EXISTS kilas_agent_events (
 id INTEGER PRIMARY KEY AUTOINCREMENT, job_id INTEGER NOT NULL REFERENCES kilas_agent_jobs(id) ON DELETE CASCADE,
 kind TEXT NOT NULL, summary TEXT NOT NULL, unread INTEGER NOT NULL DEFAULT 1, event_key TEXT UNIQUE,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS kilas_agent_artifacts (
 id INTEGER PRIMARY KEY AUTOINCREMENT, job_id INTEGER NOT NULL REFERENCES kilas_agent_jobs(id) ON DELETE CASCADE,
 step_id INTEGER NOT NULL REFERENCES kilas_agent_steps(id), name TEXT NOT NULL, media_type TEXT NOT NULL,
 content TEXT NOT NULL, digest TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(step_id,name,digest)
);
CREATE TABLE IF NOT EXISTS kilas_agent_approvals (
 id INTEGER PRIMARY KEY AUTOINCREMENT, job_id INTEGER NOT NULL REFERENCES kilas_agent_jobs(id) ON DELETE CASCADE,
 step_id INTEGER NOT NULL REFERENCES kilas_agent_steps(id), payload_json TEXT NOT NULL, digest TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','APPROVED','CONSUMED','CANCELLED')),
 expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(step_id,digest)
);
